version: "3.3"
services:
  mysql:
    image: mysql:5.7.36
    environment:
      MYSQL_DATABASE: "glovo"
      MYSQL_USER: "glovo"
      MYSQL_PASSWORD: "glovo"
      MYSQL_ROOT_PASSWORD: "root"
    volumes:
      - ./docker-compose-data/mysql:/var/lib/mysql
    ports:
      - "3306:3306"
  adminer:
    image: adminer
    restart: always
    ports:
    - 8081:8080